# contents of pyproject.toml

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "example-package-ytoh2000"
version = "0.1.0"
dependencies = [
  "numpy"
]

[project.optional-dependencies]
test = ["pytest"]